-- ACID и isolation
SHOW transaction_isolation;

BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW transaction_isolation;
ROLLBACK;

CREATE TEMP TABLE acid_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount INTEGER NOT NULL
);

INSERT INTO acid_demo (amount) VALUES (100), (200);

BEGIN;
UPDATE acid_demo SET amount = amount - 50 WHERE id = 1;
UPDATE acid_demo SET amount = amount + 50 WHERE id = 2;
SELECT * FROM acid_demo ORDER BY id;
ROLLBACK;
SELECT * FROM acid_demo ORDER BY id;
