-- Практика: ACID и isolation

-- Задание 1: show_default_isolation
-- Покажи текущий уровень isolation.
SHOW transaction_isolation;

-- Задание 2: set_repeatable_read_transaction
-- Открой транзакцию и явно переключи её в REPEATABLE READ.
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW transaction_isolation;
ROLLBACK;

-- Задание 3: temp_atomicity_demo
-- На TEMP TABLE покажи, что изменения внутри транзакции можно откатить целиком.
DROP TABLE IF EXISTS acid_demo;
CREATE TEMP TABLE acid_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount INTEGER NOT NULL
);

INSERT INTO acid_demo (amount) VALUES (100), (200);

BEGIN;
UPDATE acid_demo SET amount = amount - 50 WHERE id = 1;
UPDATE acid_demo SET amount = amount + 50 WHERE id = 2;
SELECT * FROM acid_demo ORDER BY id;
ROLLBACK;
SELECT * FROM acid_demo ORDER BY id;

-- Задание 4: write_acid_notes
-- Кратко зафиксируй смысл ACID.
SELECT 'Atomicity = all-or-nothing; Consistency = constraints stay valid; Isolation = concurrent work gets controlled visibility; Durability = COMMIT is persisted.' AS note;

-- Задание 5: compare_read_committed_vs_repeatable_read
-- Сравни READ COMMITTED и REPEATABLE READ одной строкой.
SELECT 'READ COMMITTED can see newly committed rows between statements; REPEATABLE READ keeps one snapshot for the whole transaction.' AS note;
