-- DDL basics
-- Примеры выполняй как единый script: транзакция откатит изменения.

BEGIN;

-- Пример 1: создать новую таблицу.
CREATE TABLE qa_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    color TEXT NOT NULL
);

-- Пример 2: изменить структуру таблицы.
ALTER TABLE qa_labels
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- Пример 3: посмотреть структуру таблицы через information_schema.
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'qa_labels'
ORDER BY ordinal_position;

ROLLBACK;
