-- Практика: DDL basics

-- Задание 1: create_environments_table
-- Напиши CREATE TABLE environments с колонками:
-- id identity primary key, name text not null, base_url text not null, is_active boolean not null default true.
DROP TABLE IF EXISTS environments;
CREATE TABLE environments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_url TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Задание 2: alter_environments_add_owner
-- Напиши ALTER TABLE, который добавляет колонку owner_name TEXT в environments.
ALTER TABLE environments
ADD COLUMN owner_name TEXT;

-- Задание 3: create_releases_table
-- Напиши CREATE TABLE releases с id identity, version text not null, released_at date.
DROP TABLE IF EXISTS releases;
CREATE TABLE releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL,
    released_at DATE
);

-- Задание 4: drop_temp_audit_log
-- Напиши DROP TABLE IF EXISTS temp_audit_log.
DROP TABLE IF EXISTS temp_audit_log;

-- Задание 5: create_service_health_table
-- Напиши CREATE TABLE service_health с id identity, service_name text not null, status text not null.
DROP TABLE IF EXISTS service_health;
CREATE TABLE service_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    status TEXT NOT NULL
);
