-- Postgres types и identity columns
-- Примеры выполняй в транзакции.

BEGIN;

CREATE TABLE typed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    is_success BOOLEAN NOT NULL,
    score NUMERIC(10, 2) NOT NULL,
    happened_on DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO typed_events (event_name, is_success, score, happened_on)
VALUES ('nightly-regression', TRUE, 98.50, DATE '2026-04-15')
RETURNING id, event_name, is_success, score, happened_on, created_at;

SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'typed_events'
ORDER BY ordinal_position;

ROLLBACK;
