-- Практика: Postgres types и identity columns

-- Задание 1: typed_table_for_incidents
-- Напиши CREATE TABLE incidents с колонками:
-- id identity, title text, severity text, is_open boolean, created_at timestamptz.
DROP TABLE IF EXISTS incidents_typed;
CREATE TABLE incidents_typed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    severity TEXT,
    is_open BOOLEAN,
    created_at TIMESTAMPTZ
);

-- Задание 2: numeric_metric_table
-- Напиши CREATE TABLE quality_metrics с колонками id identity, metric_name text, metric_value numeric(10, 2).
DROP TABLE IF EXISTS quality_metrics;
CREATE TABLE quality_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name TEXT,
    metric_value NUMERIC(10, 2)
);

-- Задание 3: date_vs_timestamp_table
-- Напиши CREATE TABLE releases_calendar с release_date date и created_at timestamptz.
DROP TABLE IF EXISTS releases_calendar;
CREATE TABLE releases_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_date DATE,
    created_at TIMESTAMPTZ
);

-- Задание 4: insert_without_manual_id
-- Напиши INSERT в таблицу с identity id без передачи id вручную.
INSERT INTO incidents_typed (title, severity, is_open, created_at)
VALUES ('Smoke regression', 'high', TRUE, NOW())
RETURNING id, title;

-- Задание 5: cast_timestamp_to_text
-- Напиши SELECT с приведением closed_at::text из tasks.
SELECT id,
       closed_at::text AS closed_at_text
FROM tasks
ORDER BY id;
