CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    team TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    assignee_id BIGINT NOT NULL REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('open', 'in_progress', 'blocked', 'closed')),
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    estimate_points INTEGER NOT NULL CHECK (estimate_points > 0),
    closed_at TIMESTAMPTZ NULL
);

CREATE TABLE test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    area TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'critical'))
);

CREATE TABLE test_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES test_cases(id),
    status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'blocked')),
    executed_by BIGINT NOT NULL REFERENCES users(id),
    duration_seconds NUMERIC(10, 2) NOT NULL CHECK (duration_seconds >= 0),
    executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE defects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('minor', 'major', 'critical')),
    status TEXT NOT NULL CHECK (status IN ('open', 'in_progress', 'fixed', 'closed')),
    task_id BIGINT NULL REFERENCES tasks(id),
    reported_by BIGINT NOT NULL REFERENCES users(id),
    reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
