-- Мини-проект: small schema
-- Создай свою маленькую Postgres-схему и добавь demo flow.

DROP TABLE IF EXISTS demo_service_checks;
DROP TABLE IF EXISTS demo_services;

-- create_schema
CREATE TABLE demo_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    owner_team TEXT NOT NULL
);

CREATE TABLE demo_service_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES demo_services(id),
    check_name TEXT NOT NULL,
    is_passing BOOLEAN NOT NULL
);

-- seed_data
INSERT INTO demo_services (service_name, owner_team)
VALUES ('billing-api', 'api'),
       ('web-frontend', 'web');

INSERT INTO demo_service_checks (service_id, check_name, is_passing)
VALUES (1, 'health', TRUE),
       (1, 'smoke', FALSE),
       (2, 'health', TRUE);

-- list_tables
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name LIKE 'demo_%'
ORDER BY table_name;

-- query_overview
SELECT s.service_name,
       COUNT(c.id) AS checks_total,
       COUNT(*) FILTER (WHERE c.is_passing = FALSE) AS failing_checks
FROM demo_services AS s
LEFT JOIN demo_service_checks AS c ON c.service_id = s.id
GROUP BY s.id, s.service_name
ORDER BY s.service_name;
