-- Транзакции: база
-- Примеры выполняй на базе zero_to_qa.

-- Пример 1: изменение внутри транзакции и откат.
SELECT id, status, closed_at
FROM tasks
WHERE id = 1;

BEGIN;

UPDATE tasks
SET status = 'closed',
    closed_at = TIMESTAMPTZ '2026-04-15 12:00:00+03'
WHERE id = 1;

SELECT id, status, closed_at
FROM tasks
WHERE id = 1;

ROLLBACK;

SELECT id, status, closed_at
FROM tasks
WHERE id = 1;

-- Пример 2: COMMIT на временной таблице, чтобы не портить основной dataset.
CREATE TEMP TABLE tx_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL
);

BEGIN;

INSERT INTO tx_demo (label)
VALUES ('inside transaction');

COMMIT;

SELECT id, label
FROM tx_demo
ORDER BY id;

DROP TABLE tx_demo;
