-- Constraints и integrity
SELECT con.conname AS constraint_name,
       pg_get_constraintdef(con.oid) AS definition
FROM pg_constraint AS con
JOIN pg_class AS rel ON rel.oid = con.conrelid
WHERE rel.relname = 'tasks'
ORDER BY con.conname;

CREATE TEMP TABLE integrity_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    severity TEXT NOT NULL CHECK (severity IN ('minor', 'major', 'critical'))
);

INSERT INTO integrity_demo (code, severity)
VALUES ('BUG-1', 'major'), ('BUG-2', 'critical');

SELECT * FROM integrity_demo ORDER BY id;
