-- Практика: constraints и integrity

-- Задание 1: list_constraints_for_tasks
-- Покажи ограничения на таблице tasks.
SELECT con.conname AS constraint_name,
       pg_get_constraintdef(con.oid) AS definition
FROM pg_constraint AS con
JOIN pg_class AS rel ON rel.oid = con.conrelid
WHERE rel.relname = 'tasks'
ORDER BY con.conname;

-- Задание 2: create_unique_check_demo
-- Создай TEMP TABLE с UNIQUE и CHECK.
DROP TABLE IF EXISTS integrity_demo;
CREATE TEMP TABLE integrity_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    severity TEXT NOT NULL CHECK (severity IN ('minor', 'major', 'critical'))
);

INSERT INTO integrity_demo (code, severity)
VALUES ('BUG-1', 'major'),
       ('BUG-2', 'critical');

SELECT * FROM integrity_demo ORDER BY id;

-- Задание 3: create_fk_demo
-- Покажи отдельный TEMP TABLE demo с FOREIGN KEY.
DROP TABLE IF EXISTS integrity_child;
DROP TABLE IF EXISTS integrity_parent;
CREATE TEMP TABLE integrity_parent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL UNIQUE
);

CREATE TEMP TABLE integrity_child (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT NOT NULL REFERENCES integrity_parent(id),
    note TEXT NOT NULL
);

INSERT INTO integrity_parent (label)
VALUES ('task-group-a'), ('task-group-b');

INSERT INTO integrity_child (parent_id, note)
VALUES (1, 'linked row 1'),
       (2, 'linked row 2');

SELECT p.id AS parent_id,
       p.label,
       c.id AS child_id,
       c.note
FROM integrity_parent AS p
LEFT JOIN integrity_child AS c ON c.parent_id = p.id
ORDER BY p.id, c.id;

-- Задание 4: integrity_rule_comments
-- Кратко объясни роль основных ограничений.
SELECT 'UNIQUE protects business identifiers, CHECK protects allowed values, and FOREIGN KEY protects references between tables.' AS note;

-- Задание 5: explain_data_quality_link
-- Объясни связь integrity и data quality.
SELECT 'Constraints stop invalid states at write time, so later quality checks spend less effort searching for preventable bad data.' AS note;
