-- Ключи и constraints
-- Примеры выполняй в транзакции.

BEGIN;

CREATE TABLE qa_environments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    base_url TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE env_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id BIGINT NOT NULL REFERENCES qa_environments(id),
    status TEXT NOT NULL CHECK (status IN ('passed', 'failed')),
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

SELECT constraint_name, constraint_type
FROM information_schema.table_constraints
WHERE table_schema = 'public'
  AND table_name IN ('qa_environments', 'env_checks')
ORDER BY table_name, constraint_type, constraint_name;

ROLLBACK;
