-- Практика: ключи и constraints

-- Задание 1: define_primary_key
-- Напиши CREATE TABLE teams с PRIMARY KEY по id.
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Задание 2: define_foreign_key
-- Напиши CREATE TABLE team_members, где team_id REFERENCES teams(id).
CREATE TABLE team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES teams(id),
    member_name TEXT NOT NULL
);

-- Задание 3: add_unique_constraint
-- Напиши CREATE TABLE qa_users, где email TEXT UNIQUE NOT NULL.
DROP TABLE IF EXISTS qa_users;
CREATE TABLE qa_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL
);

-- Задание 4: add_check_constraint
-- Напиши CREATE TABLE incidents с CHECK по severity IN ('low', 'medium', 'high').
DROP TABLE IF EXISTS incidents;
CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high'))
);

-- Задание 5: combine_constraints
-- Напиши CREATE TABLE releases с identity id, version TEXT UNIQUE NOT NULL и deployed_at TIMESTAMPTZ.
DROP TABLE IF EXISTS training_releases;
CREATE TABLE training_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT UNIQUE NOT NULL,
    deployed_at TIMESTAMPTZ
);
